### ISSUE TITLE
its didnt Run

### ISSUE THREAD

**Issue by pskirankumar** [kurema/BookViewerApp3#3]
1.Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BrowserControl\bin\x64\Debug\BrowserControl.dll' could not be found	BookViewerApp	2.C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BookViewerApp\CSC	1	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\FileExplorerControl\bin\x64\Debug\FileExplorerControl.dll' could not be found	BookViewerApp	3.C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BookViewerApp\CSC	1	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to get MD5 checksum for the key file "BookViewerApp_TemporaryKey.pfx". Could not find file 4.'C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BrowserControl\BookViewerApp_TemporaryKey.pfx'.	BrowserControl			
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "CompileXaml" task returned false but did not log an error.	BookViewerApp

**Comment by pskirankumar** [comment]
1.Severity Code Description Project File Line Suppression State
Error CS0006 Metadata file 'C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BrowserControl\bin\x64\Debug\BrowserControl.dll' could not be found BookViewerApp 2.C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BookViewerApp\CSC 1 Active
Severity Code Description Project File Line Suppression State
Error CS0006 Metadata file 'C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\FileExplorerControl\bin\x64\Debug\FileExplorerControl.dll' could not be found BookViewerApp 3.C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BookViewerApp\CSC 1 Active
Severity Code Description Project File Line Suppression State
Error Unable to get MD5 checksum for the key file "BookViewerApp_TemporaryKey.pfx". Could not find file 4.'C:\Users\HP\Downloads\BookViewerApp3-master (4)\BookViewerApp3-master\BrowserControl\BookViewerApp_TemporaryKey.pfx'. BrowserControl
Severity Code Description Project File Line Suppression State
Error The "CompileXaml" task returned false but did not log an error. BookViewerApp

**Comment by kurema** [comment]
Thank you for your report.

"BookViewerApp_TemporaryKey.pfx" is not included in the repository because it should be kept secret.
Adding your own pfx file to all three projects or just disable singing may fix the issue.

![image](https://user-images.githubusercontent.com/10556974/91781988-cd00eb00-ec36-11ea-993a-d88996bea299.png)

Or if you just want to try, [get it from Microsoft](https://www.microsoft.com/store/apps/9N607JHLBCZB).

**Comment by pskirankumar** [comment]
Thanks alot
