### ISSUE TITLE
App crash with .NET Native enabled

### ISSUE THREAD

**Issue by kurema** [kurema/BookViewerApp3#4]
After I update VisualStudio to 16.8, app crash immediately if you build it with .NET Native turned on.
Maybe it's a issue of my computer, but I would have to halt development for a while.
Or reinstalling VS 16.7.* may fix, but I don't.

[Japanese]
.NET Nativeをオンにしてると起動時すぐ落ちます。原因不明。
あまりに意味不明でやる気が出ないのでこのアプリの開発は数週間ほど停止します。

**Comment by runceel** [comment]
On my Visual Studio 2019 16.8.2, I was not able to reproduce the issue.

1. Clone this repository
2. Remove all .fpx files on the solution explorer
3. Set Release (x86)
4. Start BookViewerApp without debugger

It worked fine on my machine.

![スクリーンショット 2020-12-04 095320](https://user-images.githubusercontent.com/79868/101107855-97ddad80-3616-11eb-881d-7053b628f50e.png)

**Comment by kurema** [comment]
Thank you for testing. This helped me a lot. Now I know I have to fix my computer.
Closing the Issue.

Discordからですね。テストありがとうございます。
bin/obj/.vsなどのファイル削除は試しているのでWindowsの問題かVSのインストールミスとかのようですね。
別環境でのテストは必要だと思っていましたが、二台目のパソコンがなかったので助かりました。

**Comment by kurema** [comment]
![image](https://user-images.githubusercontent.com/10556974/101116266-1b53ca80-3628-11eb-8a6a-95befe893753.png)

**Comment by kurema** [comment]
GitHub Actions!
Now I enabled [building on GitHub Actions](https://github.com/kurema/BookViewerApp3/blob/master/.github/workflows/releasebuilder.yml), I can debug and upload the file to store.

リリースビルドはGitHub Actionsを利用するようにしたので、リモートでビルドして対処することにしました。
一度に30分程度掛かりますが、無料なので遠慮せず使います。
ローカルではDebugでデバッグ、問題がなければリモートでReleaseビルドのテスト、でストアにアップロードの流れで。
