### ISSUE TITLE
Lower Brightness

### ISSUE THREAD

**Issue by jediMaster07** [kurema/BookViewerApp3#9]
Unable to lower the brightness of the application. There should be a feature that diminishes the brightness of the application independent of system brightness.

**Comment by kurema** [comment]
Ok. It sounds like a good idea. I think it's possible. ([API](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.display.brightnessoverride))

But I'm currently working on another project so it may take some time. It all depend on my feeling. Sorry in that case.

**Comment by kurema** [comment]
Done. I don't have laptop so I can't test now but I think this is fine.

**Comment by jediMaster07** [comment]
Hey, thank you for such a quick update. I could help you test but I am not sure how to download/install the latest build

**Comment by kurema** [comment]
This function was relatively easy. Although some other viewer apps have similar function, I didn't come up with that. Thanks.

The new version is uploaded to Microsoft Store. Please wait for some days before the new version to be delivered.
I did it  without proper dogfooding. Maybe I should have but I think it's OK. The setting is currently marked as "preview" feature.

**Comment by kurema** [comment]
I tested the functionality today at a local electronics store. It looked like OK. Closing this issue.
